spring.application.name=klutch-gaming-platform

# Server
server.port=8000

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/klutch_gaming
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=changeme
jwt.expiration=900000
jwt.refresh-expiration=2592000000

spring.profiles.active=local

# CORS
cors.allowed-origins=http://localhost:5173,http://localhost:5174

# Logging
logging.level.root=INFO
logging.level.dev.juviscript=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n